// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailSender creates a new instance of MockMailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailSender {
	mock := &MockMailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailSender is an autogenerated mock type for the MailSender type
type MockMailSender struct {
	mock.Mock
}

type MockMailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailSender) EXPECT() *MockMailSender_Expecter {
	return &MockMailSender_Expecter{mock: &_m.Mock}
}

// SendVerification provides a mock function for the type MockMailSender
func (_mock *MockMailSender) SendVerification(ctx context.Context, msg VerificationMail) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, VerificationMail) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailSender_SendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerification'
type MockMailSender_SendVerification_Call struct {
	*mock.Call
}

// SendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - msg VerificationMail
func (_e *MockMailSender_Expecter) SendVerification(ctx interface{}, msg interface{}) *MockMailSender_SendVerification_Call {
	return &MockMailSender_SendVerification_Call{Call: _e.mock.On("SendVerification", ctx, msg)}
}

func (_c *MockMailSender_SendVerification_Call) Run(run func(ctx context.Context, msg VerificationMail)) *MockMailSender_SendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 VerificationMail
		if args[1] != nil {
			arg1 = args[1].(VerificationMail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailSender_SendVerification_Call) Return(err error) *MockMailSender_SendVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailSender_SendVerification_Call) RunAndReturn(run func(ctx context.Context, msg VerificationMail) error) *MockMailSender_SendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOauthClientsRepository creates a new instance of MockOauthClientsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOauthClientsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOauthClientsRepository {
	mock := &MockOauthClientsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOauthClientsRepository is an autogenerated mock type for the OauthClientsRepository type
type MockOauthClientsRepository struct {
	mock.Mock
}

type MockOauthClientsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOauthClientsRepository) EXPECT() *MockOauthClientsRepository_Expecter {
	return &MockOauthClientsRepository_Expecter{mock: &_m.Mock}
}

// GetOauthClientRedirectUrisByClientID provides a mock function for the type MockOauthClientsRepository
func (_mock *MockOauthClientsRepository) GetOauthClientRedirectUrisByClientID(ctx context.Context, clientID uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetOauthClientRedirectUrisByClientID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOauthClientRedirectUrisByClientID'
type MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call struct {
	*mock.Call
}

// GetOauthClientRedirectUrisByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockOauthClientsRepository_Expecter) GetOauthClientRedirectUrisByClientID(ctx interface{}, clientID interface{}) *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call {
	return &MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call{Call: _e.mock.On("GetOauthClientRedirectUrisByClientID", ctx, clientID)}
}

func (_c *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call) Return(strings []string, err error) *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) ([]string, error)) *MockOauthClientsRepository_GetOauthClientRedirectUrisByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOauthClientsUsecase creates a new instance of MockOauthClientsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOauthClientsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOauthClientsUsecase {
	mock := &MockOauthClientsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOauthClientsUsecase is an autogenerated mock type for the OauthClientsUsecase type
type MockOauthClientsUsecase struct {
	mock.Mock
}

type MockOauthClientsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOauthClientsUsecase) EXPECT() *MockOauthClientsUsecase_Expecter {
	return &MockOauthClientsUsecase_Expecter{mock: &_m.Mock}
}

// EffectiveRedirectURI provides a mock function for the type MockOauthClientsUsecase
func (_mock *MockOauthClientsUsecase) EffectiveRedirectURI(ctx context.Context, clientID uuid.UUID, requested string) (string, error) {
	ret := _mock.Called(ctx, clientID, requested)

	if len(ret) == 0 {
		panic("no return value specified for EffectiveRedirectURI")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return returnFunc(ctx, clientID, requested)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = returnFunc(ctx, clientID, requested)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, clientID, requested)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthClientsUsecase_EffectiveRedirectURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EffectiveRedirectURI'
type MockOauthClientsUsecase_EffectiveRedirectURI_Call struct {
	*mock.Call
}

// EffectiveRedirectURI is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - requested string
func (_e *MockOauthClientsUsecase_Expecter) EffectiveRedirectURI(ctx interface{}, clientID interface{}, requested interface{}) *MockOauthClientsUsecase_EffectiveRedirectURI_Call {
	return &MockOauthClientsUsecase_EffectiveRedirectURI_Call{Call: _e.mock.On("EffectiveRedirectURI", ctx, clientID, requested)}
}

func (_c *MockOauthClientsUsecase_EffectiveRedirectURI_Call) Run(run func(ctx context.Context, clientID uuid.UUID, requested string)) *MockOauthClientsUsecase_EffectiveRedirectURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOauthClientsUsecase_EffectiveRedirectURI_Call) Return(s string, err error) *MockOauthClientsUsecase_EffectiveRedirectURI_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOauthClientsUsecase_EffectiveRedirectURI_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, requested string) (string, error)) *MockOauthClientsUsecase_EffectiveRedirectURI_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateClientRedirectURI provides a mock function for the type MockOauthClientsUsecase
func (_mock *MockOauthClientsUsecase) ValidateClientRedirectURI(ctx context.Context, clientID uuid.UUID, redirectURI string) (bool, error) {
	ret := _mock.Called(ctx, clientID, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClientRedirectURI")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, clientID, redirectURI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, clientID, redirectURI)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, clientID, redirectURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthClientsUsecase_ValidateClientRedirectURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClientRedirectURI'
type MockOauthClientsUsecase_ValidateClientRedirectURI_Call struct {
	*mock.Call
}

// ValidateClientRedirectURI is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - redirectURI string
func (_e *MockOauthClientsUsecase_Expecter) ValidateClientRedirectURI(ctx interface{}, clientID interface{}, redirectURI interface{}) *MockOauthClientsUsecase_ValidateClientRedirectURI_Call {
	return &MockOauthClientsUsecase_ValidateClientRedirectURI_Call{Call: _e.mock.On("ValidateClientRedirectURI", ctx, clientID, redirectURI)}
}

func (_c *MockOauthClientsUsecase_ValidateClientRedirectURI_Call) Run(run func(ctx context.Context, clientID uuid.UUID, redirectURI string)) *MockOauthClientsUsecase_ValidateClientRedirectURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOauthClientsUsecase_ValidateClientRedirectURI_Call) Return(b bool, err error) *MockOauthClientsUsecase_ValidateClientRedirectURI_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOauthClientsUsecase_ValidateClientRedirectURI_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, redirectURI string) (bool, error)) *MockOauthClientsUsecase_ValidateClientRedirectURI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailVerificationStore creates a new instance of MockEmailVerificationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationStore {
	mock := &MockEmailVerificationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationStore is an autogenerated mock type for the EmailVerificationStore type
type MockEmailVerificationStore struct {
	mock.Mock
}

type MockEmailVerificationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationStore) EXPECT() *MockEmailVerificationStore_Expecter {
	return &MockEmailVerificationStore_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockEmailVerificationStore
func (_mock *MockEmailVerificationStore) Consume(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationStore_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockEmailVerificationStore_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockEmailVerificationStore_Expecter) Consume(ctx interface{}, token interface{}) *MockEmailVerificationStore_Consume_Call {
	return &MockEmailVerificationStore_Consume_Call{Call: _e.mock.On("Consume", ctx, token)}
}

func (_c *MockEmailVerificationStore_Consume_Call) Run(run func(ctx context.Context, token string)) *MockEmailVerificationStore_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationStore_Consume_Call) Return(uUID uuid.UUID, err error) *MockEmailVerificationStore_Consume_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockEmailVerificationStore_Consume_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, error)) *MockEmailVerificationStore_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockEmailVerificationStore
func (_mock *MockEmailVerificationStore) Save(ctx context.Context, token string, userID uuid.UUID, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockEmailVerificationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID uuid.UUID
//   - ttl time.Duration
func (_e *MockEmailVerificationStore_Expecter) Save(ctx interface{}, token interface{}, userID interface{}, ttl interface{}) *MockEmailVerificationStore_Save_Call {
	return &MockEmailVerificationStore_Save_Call{Call: _e.mock.On("Save", ctx, token, userID, ttl)}
}

func (_c *MockEmailVerificationStore_Save_Call) Run(run func(ctx context.Context, token string, userID uuid.UUID, ttl time.Duration)) *MockEmailVerificationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailVerificationStore_Save_Call) Return(err error) *MockEmailVerificationStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationStore_Save_Call) RunAndReturn(run func(ctx context.Context, token string, userID uuid.UUID, ttl time.Duration) error) *MockEmailVerificationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOauthUsersRepository creates a new instance of MockOauthUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOauthUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOauthUsersRepository {
	mock := &MockOauthUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOauthUsersRepository is an autogenerated mock type for the OauthUsersRepository type
type MockOauthUsersRepository struct {
	mock.Mock
}

type MockOauthUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOauthUsersRepository) EXPECT() *MockOauthUsersRepository_Expecter {
	return &MockOauthUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateOauthUser provides a mock function for the type MockOauthUsersRepository
func (_mock *MockOauthUsersRepository) CreateOauthUser(ctx context.Context, nickname string, email string, password string) (User, error) {
	ret := _mock.Called(ctx, nickname, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateOauthUser")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (User, error)); ok {
		return returnFunc(ctx, nickname, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) User); ok {
		r0 = returnFunc(ctx, nickname, email, password)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, nickname, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthUsersRepository_CreateOauthUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOauthUser'
type MockOauthUsersRepository_CreateOauthUser_Call struct {
	*mock.Call
}

// CreateOauthUser is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - email string
//   - password string
func (_e *MockOauthUsersRepository_Expecter) CreateOauthUser(ctx interface{}, nickname interface{}, email interface{}, password interface{}) *MockOauthUsersRepository_CreateOauthUser_Call {
	return &MockOauthUsersRepository_CreateOauthUser_Call{Call: _e.mock.On("CreateOauthUser", ctx, nickname, email, password)}
}

func (_c *MockOauthUsersRepository_CreateOauthUser_Call) Run(run func(ctx context.Context, nickname string, email string, password string)) *MockOauthUsersRepository_CreateOauthUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOauthUsersRepository_CreateOauthUser_Call) Return(user User, err error) *MockOauthUsersRepository_CreateOauthUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockOauthUsersRepository_CreateOauthUser_Call) RunAndReturn(run func(ctx context.Context, nickname string, email string, password string) (User, error)) *MockOauthUsersRepository_CreateOauthUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOauthUserEmailVerified provides a mock function for the type MockOauthUsersRepository
func (_mock *MockOauthUsersRepository) MarkOauthUserEmailVerified(ctx context.Context, userID uuid.UUID) (User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOauthUserEmailVerified")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthUsersRepository_MarkOauthUserEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOauthUserEmailVerified'
type MockOauthUsersRepository_MarkOauthUserEmailVerified_Call struct {
	*mock.Call
}

// MarkOauthUserEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOauthUsersRepository_Expecter) MarkOauthUserEmailVerified(ctx interface{}, userID interface{}) *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call {
	return &MockOauthUsersRepository_MarkOauthUserEmailVerified_Call{Call: _e.mock.On("MarkOauthUserEmailVerified", ctx, userID)}
}

func (_c *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call) Return(user User, err error) *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (User, error)) *MockOauthUsersRepository_MarkOauthUserEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOauthUsersUsecase creates a new instance of MockOauthUsersUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOauthUsersUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOauthUsersUsecase {
	mock := &MockOauthUsersUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOauthUsersUsecase is an autogenerated mock type for the OauthUsersUsecase type
type MockOauthUsersUsecase struct {
	mock.Mock
}

type MockOauthUsersUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOauthUsersUsecase) EXPECT() *MockOauthUsersUsecase_Expecter {
	return &MockOauthUsersUsecase_Expecter{mock: &_m.Mock}
}

// RegisterOauthUser provides a mock function for the type MockOauthUsersUsecase
func (_mock *MockOauthUsersUsecase) RegisterOauthUser(ctx context.Context, nickname string, email string, password string) (UserResponse, error) {
	ret := _mock.Called(ctx, nickname, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOauthUser")
	}

	var r0 UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (UserResponse, error)); ok {
		return returnFunc(ctx, nickname, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) UserResponse); ok {
		r0 = returnFunc(ctx, nickname, email, password)
	} else {
		r0 = ret.Get(0).(UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, nickname, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthUsersUsecase_RegisterOauthUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOauthUser'
type MockOauthUsersUsecase_RegisterOauthUser_Call struct {
	*mock.Call
}

// RegisterOauthUser is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
//   - email string
//   - password string
func (_e *MockOauthUsersUsecase_Expecter) RegisterOauthUser(ctx interface{}, nickname interface{}, email interface{}, password interface{}) *MockOauthUsersUsecase_RegisterOauthUser_Call {
	return &MockOauthUsersUsecase_RegisterOauthUser_Call{Call: _e.mock.On("RegisterOauthUser", ctx, nickname, email, password)}
}

func (_c *MockOauthUsersUsecase_RegisterOauthUser_Call) Run(run func(ctx context.Context, nickname string, email string, password string)) *MockOauthUsersUsecase_RegisterOauthUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOauthUsersUsecase_RegisterOauthUser_Call) Return(userResponse UserResponse, err error) *MockOauthUsersUsecase_RegisterOauthUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockOauthUsersUsecase_RegisterOauthUser_Call) RunAndReturn(run func(ctx context.Context, nickname string, email string, password string) (UserResponse, error)) *MockOauthUsersUsecase_RegisterOauthUser_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type MockOauthUsersUsecase
func (_mock *MockOauthUsersUsecase) VerifyEmail(ctx context.Context, token string) (UserResponse, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (UserResponse, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) UserResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauthUsersUsecase_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockOauthUsersUsecase_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockOauthUsersUsecase_Expecter) VerifyEmail(ctx interface{}, token interface{}) *MockOauthUsersUsecase_VerifyEmail_Call {
	return &MockOauthUsersUsecase_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *MockOauthUsersUsecase_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *MockOauthUsersUsecase_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOauthUsersUsecase_VerifyEmail_Call) Return(userResponse UserResponse, err error) *MockOauthUsersUsecase_VerifyEmail_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockOauthUsersUsecase_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, token string) (UserResponse, error)) *MockOauthUsersUsecase_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
