// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthClient struct {
	ID                    pgtype.UUID
	ClientID              pgtype.UUID
	ClientName            string
	ClientType            string
	ClientSecret          pgtype.Text
	ClientSecretExpiresAt pgtype.Timestamptz
	RedirectUris          []string
	CreateTime            pgtype.Timestamptz
	Status                string
}

type OauthUser struct {
	UserID        pgtype.UUID
	Nickname      string
	Email         string
	Password      string
	IsActive      bool
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
}
