// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOauthUser = `-- name: CreateOauthUser :one
INSERT INTO oauth_users (
    nickname,
    email,
    password
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (email) DO NOTHING
RETURNING
    user_id,
    nickname,
    email,
    password,
    is_active,
    email_verified,
    created_at
`

type CreateOauthUserParams struct {
	Nickname string
	Email    string
	Password string
}

func (q *Queries) CreateOauthUser(ctx context.Context, arg CreateOauthUserParams) (OauthUser, error) {
	row := q.db.QueryRow(ctx, createOauthUser, arg.Nickname, arg.Email, arg.Password)
	var i OauthUser
	err := row.Scan(
		&i.UserID,
		&i.Nickname,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getOauthUserByEmail = `-- name: GetOauthUserByEmail :one
SELECT
    user_id,
    nickname,
    email,
    password,
    is_active,
    email_verified,
    created_at
FROM oauth_users
WHERE email = $1
`

func (q *Queries) GetOauthUserByEmail(ctx context.Context, email string) (OauthUser, error) {
	row := q.db.QueryRow(ctx, getOauthUserByEmail, email)
	var i OauthUser
	err := row.Scan(
		&i.UserID,
		&i.Nickname,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const markOauthUserEmailVerified = `-- name: MarkOauthUserEmailVerified :one
UPDATE oauth_users
SET email_verified = true
WHERE user_id = $1
RETURNING
    user_id,
    nickname,
    email,
    password,
    is_active,
    email_verified,
    created_at
`

func (q *Queries) MarkOauthUserEmailVerified(ctx context.Context, userID pgtype.UUID) (OauthUser, error) {
	row := q.db.QueryRow(ctx, markOauthUserEmailVerified, userID)
	var i OauthUser
	err := row.Scan(
		&i.UserID,
		&i.Nickname,
		&i.Email,
		&i.Password,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}
