// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOauthClient = `-- name: CreateOauthClient :one
INSERT INTO oauth_clients (
    client_id,
    client_name,
    client_type,
    client_secret,
    client_secret_expires_at,
    redirect_uris,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    client_id,
    client_name,
    client_type,
    client_secret,
    client_secret_expires_at,
    redirect_uris,
    create_time,
    status
`

type CreateOauthClientParams struct {
	ClientID              pgtype.UUID
	ClientName            string
	ClientType            string
	ClientSecret          pgtype.Text
	ClientSecretExpiresAt pgtype.Timestamptz
	RedirectUris          []string
	Status                string
}

func (q *Queries) CreateOauthClient(ctx context.Context, arg CreateOauthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOauthClient,
		arg.ClientID,
		arg.ClientName,
		arg.ClientType,
		arg.ClientSecret,
		arg.ClientSecretExpiresAt,
		arg.RedirectUris,
		arg.Status,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecret,
		&i.ClientSecretExpiresAt,
		&i.RedirectUris,
		&i.CreateTime,
		&i.Status,
	)
	return i, err
}

const getOauthClientRedirectUrisByClientID = `-- name: GetOauthClientRedirectUrisByClientID :one
SELECT redirect_uris
FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetOauthClientRedirectUrisByClientID(ctx context.Context, clientID pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getOauthClientRedirectUrisByClientID, clientID)
	var redirect_uris []string
	err := row.Scan(&redirect_uris)
	return redirect_uris, err
}

const oauthClientExistsByClientID = `-- name: OauthClientExistsByClientID :one
SELECT EXISTS (
    SELECT 1
    FROM oauth_clients
    WHERE client_id = $1
) AS client_exists
`

func (q *Queries) OauthClientExistsByClientID(ctx context.Context, clientID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, oauthClientExistsByClientID, clientID)
	var client_exists bool
	err := row.Scan(&client_exists)
	return client_exists, err
}
